/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual.Pasajero;

import Model.Usuarios.Administrador.Modulos.AdminViajes;
import Model.Usuarios.Monto;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;

/**
 * @author NexBorn
 */
public class JComprarBoleto extends javax.swing.JPanel {
    private AdminViajes viajeSelected = new AdminViajes();
    DecimalFormat df = new DecimalFormat("###.##");
    Monto monto = new Monto();

    /**
     * Creates new form JComprarBoleto
     */
    public JComprarBoleto() {
        initComponents();
        rbEfectivo.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnSelecionarViaje = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        rbEfectivo = new javax.swing.JRadioButton();
        rbTarjeta = new javax.swing.JRadioButton();
        btnSeleccionarAsientos = new javax.swing.JButton();
        lblHorario = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lblPrecioTotal1 = new javax.swing.JLabel();
        lblCooperativa = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblPartida = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblValorUnitario = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(770, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Destino:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Cooperativa:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Núm. de Boletos:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Horario:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("Total a pagar:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        btnSelecionarViaje.setBackground(new java.awt.Color(255, 255, 255));
        btnSelecionarViaje.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSelecionarViaje.setText("Seleccionar Viaje");
        btnSelecionarViaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSelecionarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarViajeActionPerformed(evt);
            }
        });
        jPanel2.add(btnSelecionarViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 156, 33));

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel13.setText("Metodo de pago:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        rbEfectivo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        rbEfectivo.setText("Efectivo");
        rbEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEfectivoActionPerformed(evt);
            }
        });
        jPanel2.add(rbEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, -1, -1));

        rbTarjeta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbTarjeta.setText("Tarjeta");
        rbTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTarjetaActionPerformed(evt);
            }
        });
        jPanel2.add(rbTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        btnSeleccionarAsientos.setBackground(new java.awt.Color(255, 255, 255));
        btnSeleccionarAsientos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSeleccionarAsientos.setText("Seleccionar asiento");
        btnSeleccionarAsientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSeleccionarAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarAsientosActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionarAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 156, 33));

        lblHorario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblHorario.setText("?");
        jPanel2.add(lblHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setText("Partida:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 80, -1));

        lblPrecioTotal1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPrecioTotal1.setText("?");
        lblPrecioTotal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        jPanel2.add(lblPrecioTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, 20));

        lblCooperativa.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblCooperativa.setText("?");
        jPanel2.add(lblCooperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        lblDestino.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDestino.setText("?");
        jPanel2.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel15.setText("Iva %12:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        lblIva.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblIva.setText("?");
        lblIva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        jPanel2.add(lblIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel16.setText("SubTotal");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        lblSubtotal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblSubtotal.setText("?");
        lblSubtotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        jPanel2.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, -1, -1));

        lblPartida.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPartida.setText("?");
        jPanel2.add(lblPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        btnComprar.setBackground(new java.awt.Color(255, 255, 255));
        btnComprar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnComprar.setText("Comprar Boleto");
        btnComprar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel2.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 156, 33));

        jLabel1.setText("Selecciona el viaje, de acuerdo con el tiempo y costo que se mostrará");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel17.setText("Valor unitario:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, 20));

        lblValorUnitario.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblValorUnitario.setText("?");
        lblValorUnitario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        jPanel2.add(lblValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 710, 410));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel10.setText("Venta Boleto");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 204, 255));
        jLabel11.setText("Perfil");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel12.setText(" > Comprar boleto");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rbEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEfectivoActionPerformed
        // TODO add your handling code here:
        if(rbTarjeta.isSelected()){
            rbEfectivo.setSelected(true);
            rbTarjeta.setSelected(false);
            return;
        }
        rbEfectivo.setSelected(true);
    }//GEN-LAST:event_rbEfectivoActionPerformed

    private void rbTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTarjetaActionPerformed
        // TODO add your handling code here:
        if(rbEfectivo.isSelected()){
            rbTarjeta.setSelected(true);
            rbEfectivo.setSelected(false);
            return;
        }
        rbTarjeta.setSelected(true);
    }//GEN-LAST:event_rbTarjetaActionPerformed

    private void btnSelecionarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarViajeActionPerformed
        // TODO add your handling code here:
        FrmMostrarViajes frmMostrarViajes = new FrmMostrarViajes(viajeSelected);
        frmMostrarViajes.setVisible(true);
        frmMostrarViajes.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                super.windowClosed(e);
                if (viajeSelected != null) {
                    lblCooperativa.setText(viajeSelected.getNombreCooperativa());
                    lblPartida.setText(viajeSelected.getPartida());
                    lblDestino.setText(viajeSelected.getDestino());
                    lblHorario.setText(viajeSelected.getHora());
                    lblValorUnitario.setText("$ " + viajeSelected.getValor());
                }
            }
        });
    }//GEN-LAST:event_btnSelecionarViajeActionPerformed

    /**
     * Inicia un Frame donde mostrar al jugador mostrar los asientos
     * @param evt Evento
     */
    private void btnSeleccionarAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarAsientosActionPerformed
        // TODO add your handling code here:
        new FrmAsientos(viajeSelected.getBus()).setVisible(true);
    }//GEN-LAST:event_btnSeleccionarAsientosActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * Mostrar el valor del monto en tiempo real y evitamos una exepcion negativa
     *
     * @param evt
     */
    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // TODO add your handling code here:
        int unidades = (int) jSpinner1.getValue();
        if (unidades > 0) {
            double subtotal = unidades * viajeSelected.getValor();
            double iva = subtotal * 0.12;
            double total = iva + subtotal;
            lblSubtotal.setText("$" + df.format(subtotal));
            lblIva.setText("$" + df.format(iva));
            lblPrecioTotal1.setText("$" + df.format(total));
            monto.setSubTotal(subtotal);
            monto.setIva(iva);
            monto.setTotal(total);
            return;
        }
        jSpinner1.setValue(0);
    }//GEN-LAST:event_jSpinner1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnSeleccionarAsientos;
    private javax.swing.JButton btnSelecionarViaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblCooperativa;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblPartida;
    private javax.swing.JLabel lblPrecioTotal1;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblValorUnitario;
    private javax.swing.JRadioButton rbEfectivo;
    private javax.swing.JRadioButton rbTarjeta;
    // End of variables declaration//GEN-END:variables
}
