/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual.Administrador;

import java.awt.*;
import Control.Administrador.BusesManager;
import Control.Administrador.CooperativasManager;
import Control.SingleCallBack;
import Control.Validaciones;
import Model.Usuarios.Administrador.Modulos.AdminCooperativas;

import javax.swing.*;

/**
 * @author 59397
 */
public class FrmActualizarBusAfiliado extends javax.swing.JFrame {

    /**
     * Creates new form FrmAñadirCooperativa
     */
    public FrmActualizarBusAfiliado() {
        initComponents();
        insertDataCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        txtPlaca = new JTextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        txtIDBus = new JTextField();
        btnGuardar = new JButton();
        btnCancelar = new JButton();
        jLabel5 = new JLabel();
        cmbCooperativa = new JComboBox<>();
        Nasientos = new JSpinner();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizar Bus Afiliado");
        Container contentPane = getContentPane();

        //---- jLabel1 ----
        jLabel1.setText("Actualizar Bus Afiliado");

        //---- jLabel2 ----
        jLabel2.setText("Codigo:");

        //---- jLabel3 ----
        jLabel3.setText("N\u00b0 Asientos:");

        //---- jLabel4 ----
        jLabel4.setText("Placa:");

        //---- btnGuardar ----
        btnGuardar.setIcon(new ImageIcon(getClass().getResource("/Visual/img/guardaricon.png")));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(e -> btnGuardarActionPerformed(e));

        //---- btnCancelar ----
        btnCancelar.setText("Cancelar");

        //---- jLabel5 ----
        jLabel5.setText("Cooperativa:");

        //---- cmbCooperativa ----
        cmbCooperativa.setModel(new DefaultComboBoxModel<>(new String[] {

        }));

        //---- Nasientos ----
        Nasientos.setModel(new SpinnerNumberModel(1, 1, 60, 1));

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addComponent(btnCancelar)
                            .addGap(62, 62, 62)
                            .addComponent(btnGuardar))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(133, 133, 133)
                            .addComponent(jLabel1)))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createParallelGroup()
                            .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                                .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 101, GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(contentPaneLayout.createSequentialGroup()
                                .addGroup(contentPaneLayout.createParallelGroup()
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(30, 30, 30)))
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addComponent(cmbCooperativa, GroupLayout.PREFERRED_SIZE, 240, GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIDBus, GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlaca, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addComponent(Nasientos, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE))
                    .addGap(58, 58, 58))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel1)
                    .addGap(51, 51, 51)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtIDBus, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Nasientos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtPlaca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addGap(26, 26, 26)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cmbCooperativa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(btnGuardar))
                    .addGap(69, 69, 69))
        );
        pack();
        setLocationRelativeTo(getOwner());
    }// </editor-fold>//GEN-END:initComponents

    public void insertDataCombo(){
        for (AdminCooperativas item: CooperativasManager.getInstance().getListCooperativas()){
            cmbCooperativa.addItem(item.getNombreCooperativa());
        }
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtIDBus.getText());
        int numAsientos = Integer.parseInt(Nasientos.getValue().toString());
        String placa = txtPlaca.getText();
        String coop = (String) cmbCooperativa.getSelectedItem();
        if (Validaciones.validarStrings(placa, coop)) {
            BusesManager.getInstance().updateBuses(codigo, numAsientos, placa, coop, new SingleCallBack() {
                @Override
                public void onSucces(String msg) {
                    JOptionPane.showMessageDialog(null, msg);
                }

                @Override
                public void onFailed() {
                    JOptionPane.showMessageDialog(null, "¡Ha ocurrido un problema de actualización!");
                }
            });
            return;

        }
        JOptionPane.showMessageDialog(null, "¡Rellene los campos faltantes!");
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarBusAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarBusAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarBusAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmActualizarBusAfiliado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmActualizarBusAfiliado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JTextField txtPlaca;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JTextField txtIDBus;
    private JButton btnGuardar;
    private JButton btnCancelar;
    private JLabel jLabel5;
    private JComboBox<String> cmbCooperativa;
    private JSpinner Nasientos;
    // End of variables declaration//GEN-END:variables
}
