/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual.Administrador;

import Control.Administrador.BusesManager;
import Control.Administrador.CooperativasManager;
import Control.Administrador.ViajesManager;
import Control.SingleCallBack;
import Control.Validaciones;
import Model.Usuarios.Administrador.Modulos.AdminCooperativas;


import javax.swing.*;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.Date;

/**
 * @author 59397
 */
public class FrmAñadirViaje extends javax.swing.JFrame {
    //Funciona :D
    private String selectedItem = "";

    /**
     * Creates new form FrmAñadirCooperativa
     */
    public FrmAñadirViaje() {
        initComponents();
        insertDataCombo();
        ((JTextField) jcFecha.getDateEditor()).setEditable(false);
    }

    public void insertDataCombo() {
        for (AdminCooperativas item : CooperativasManager.getInstance().getListCooperativas()) {
            cmbCooperativa.addItem(item.getNombreCooperativa());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbCooperativa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cmbhora = new javax.swing.JComboBox<>();
        txtlugarDestino = new javax.swing.JTextField();
        txtLugarDePartida = new javax.swing.JTextField();
        jcFecha = new com.toedter.calendar.JDateChooser();
        cmbBuses = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Viaje");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("Añadir Viaje");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 28, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Cooperativa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 81, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setText("Lugar de partida:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 170, 146, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setText("Lugar de destino:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 219, -1, -1));

        btnGuardar.setBackground(java.awt.SystemColor.activeCaption);
        btnGuardar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visual/img/guardaricon.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 402, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 402, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setText("Hora:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 305, -1, 21));

        cmbCooperativa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCooperativaItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbCooperativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 82, 186, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setText("Fecha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 267, -1, -1));

        cmbhora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1:00", "2:00", "3:00", "4:00", "5:00", "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", "24:00", " "}));
        getContentPane().add(cmbhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 305, 146, -1));

        txtlugarDestino.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtlugarDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtlugarDestinoKeyTyped(evt);
            }
        });
        getContentPane().add(txtlugarDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 216, 145, -1));

        txtLugarDePartida.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtLugarDePartida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLugarDePartidaKeyTyped(evt);
            }
        });
        getContentPane().add(txtLugarDePartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 167, 145, -1));
        getContentPane().add(jcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 267, 187, -1));

        getContentPane().add(cmbBuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 121, 186, -1));

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel7.setText("Bus:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setText("Valor:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 350, -1, -1));

        txtValor.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 344, 80, -1));

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setText("$");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String cooperativa = (String) cmbCooperativa.getSelectedItem();
        String lugarPartida = txtLugarDePartida.getText();
        String destino = txtlugarDestino.getText();
        long date = jcFecha.getDate().getTime();
        String bus = (String) cmbBuses.getSelectedItem();
        String hora = (String) cmbhora.getSelectedItem();
        double valor = Double.parseDouble(txtValor.getText());
        if (Validaciones.validarStrings(cooperativa, lugarPartida, destino, hora, bus) && date > 1L && valor > 0) {
            ViajesManager.getInstance().insertViaje(cooperativa, bus, lugarPartida, destino, date, hora, valor, new SingleCallBack() {
                @Override
                public void onSucces(String msg) {
                    JOptionPane.showMessageDialog(null, msg);
                }

                @Override
                public void onFailed() {
                    JOptionPane.showMessageDialog(null, "¡No se ha podido insertar los datos!");
                }
            });
            return;
        }
        JOptionPane.showMessageDialog(null, "¡Complete los campos!");
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmbCooperativaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCooperativaItemStateChanged
        // TODO add your handling code here:
        cmbBuses.removeAllItems();
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String itemselected = ((String) evt.getItem()).trim();
            if (Validaciones.validarStrings(itemselected) && !selectedItem.equals(itemselected)) {
                for (String item : BusesManager.getInstance().getBusPorCooperativa(itemselected)) {
                    cmbBuses.addItem(item);
                }
            }
        }

    }//GEN-LAST:event_cmbCooperativaItemStateChanged

    private void txtLugarDePartidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLugarDePartidaKeyTyped
        // TODO add your handling code here:
        char valida = evt.getKeyChar();
        if (!Character.isLetter(valida) && valida != KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtLugarDePartidaKeyTyped

    private void txtlugarDestinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlugarDestinoKeyTyped
        // TODO add your handling code here:
        char valida = evt.getKeyChar();
        if (!Character.isLetter(valida)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtlugarDestinoKeyTyped

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        // TODO add your handling code here:
        char valida = evt.getKeyChar();

        if (!Character.isDigit(valida)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAñadirViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAñadirViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAñadirViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAñadirViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAñadirViaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbBuses;
    private javax.swing.JComboBox<String> cmbCooperativa;
    private javax.swing.JComboBox<String> cmbhora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jcFecha;
    private javax.swing.JTextField txtLugarDePartida;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtlugarDestino;
    // End of variables declaration//GEN-END:variables
}
